"""Public desifaces-v3 shared contract surface.

Import contracts from this package rather than capability implementation modules.
"""

from .adapters import (
    derive_idempotency_key,
    make_api_error,
    make_request_context,
    normalize_error_code,
    normalize_job_state,
    stable_payload_digest,
)
from .common import (
    ActorType,
    ApiEnvelope,
    ApiError,
    ApiMeta,
    ErrorCode,
    PageInfo,
    PagedResult,
    RequestActor,
    RequestContext,
    V3ContractModel,
)
from .commerce import (
    CreditEntryType,
    CreditTransaction,
    Entitlement,
    EntitlementState,
    PriceMoney,
    PricingQuote,
)
from .domain import (
    AccountRef,
    ConversationRef,
    EntityState,
    GenerationJob,
    GenerationKind,
    GenerationRequest,
    JobState,
    MediaAsset,
    MediaKind,
    MediaRole,
    ParticipantKind,
    ParticipantRef,
    ProjectRef,
    ProviderExecution,
    ProviderExecutionState,
    SafetyDecision,
    SafetyState,
    SceneRef,
    StoryRef,
    UserRef,
)

__all__ = [
    "AccountRef",
    "ActorType",
    "ApiEnvelope",
    "ApiError",
    "ApiMeta",
    "ConversationRef",
    "CreditEntryType",
    "CreditTransaction",
    "Entitlement",
    "EntitlementState",
    "EntityState",
    "ErrorCode",
    "GenerationJob",
    "GenerationKind",
    "GenerationRequest",
    "JobState",
    "MediaAsset",
    "MediaKind",
    "MediaRole",
    "PageInfo",
    "PagedResult",
    "ParticipantKind",
    "ParticipantRef",
    "PriceMoney",
    "PricingQuote",
    "ProjectRef",
    "ProviderExecution",
    "ProviderExecutionState",
    "RequestActor",
    "RequestContext",
    "SafetyDecision",
    "SafetyState",
    "SceneRef",
    "StoryRef",
    "UserRef",
    "V3ContractModel",
    "derive_idempotency_key",
    "make_api_error",
    "make_request_context",
    "normalize_error_code",
    "normalize_job_state",
    "stable_payload_digest",
]
